version: '3.7'

networks:
  inception:
    driver: bridge

volumes:
  DataBase:
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /Users/mharriso/Desktop/Inception/volumes/DataBase
      # device: /home/mharriso/data/DataBase
  WordPress:
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /Users/mharriso/Desktop/Inception/volumes/WordPress
      # device: /home/mharriso/data/WordPress

services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: always
    networks:
      - inception
    volumes:
      - DataBase:containerPath
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    restart: always
    networks:
      - inception
    volumes:
      - WordPress:containerPath
    env_file:
      - .env
    depends_on:
      - mariadb
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    restart: always
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress


